r"""Body / paragraph / run / table walking for the docx adapter.

Converts the OOXML ``w:body`` subtree into IR blocks: paragraphs,
headings, lists, tables, and standalone display-math blocks. Inline
math (OMML / OLE MathType / Word EQ fields) is surfaced as
``$<math>...</math>$`` text embedded in the surrounding paragraph.

DAG position: depends on :mod:`._xml` (tag / serialisation helpers and
namespace constants) and :mod:`._ole` (OLE→inline-math extraction).
The orchestration entry points (:func:`parse_docx` etc.) live in the
package ``__init__`` and call into here.
"""

from __future__ import annotations

import re

from brailix.input.docx._ole import _ole_object_to_inline_math
from brailix.input.docx._xml import (
    _W_PREFIX,
    Element,
    _first,
    _first_local,
    _flatten_xml,
    _inline_math_as_text,
    _local,
    _serialize,
)
from brailix.ir.document import (
    Block,
    Heading,
    List,
    ListItem,
    MathBlock,
    Paragraph,
    Table,
    TableCell,
    TableRow,
)

_HEADING_STYLE_RE = re.compile(r"^heading\s*(\d+)$", re.IGNORECASE)

# Word lets a paragraph be a list item via either ``numPr`` (real
# numbering with a definition) or just a list-flavoured pStyle (eg.
# ``ListBullet``, ``ListNumber1``).  The style-only path is common in
# documents generated by python-docx or by Word's "Apply Style"
# command without explicit numbering, so we detect both.  The regex
# below matches the bullet / number / dash / continuation variants
# Word ships out of the box plus their numbered siblings (``ListNumber``,
# ``ListNumber2``, ...).
_LIST_STYLE_RE = re.compile(
    r"^list\s*(bullet|number|dash|paragraph|continue)(\d*)$",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Body walker
# ---------------------------------------------------------------------------


def _iter_body_blocks(body: Element, *, ole_blobs: dict[str, bytes] | None = None):
    """Yield IR blocks from ``w:body`` in document order.

    Consecutive list-item paragraphs are merged into one :class:`List`
    so the IR matches what users see in Word (no per-line ``List``
    wrapper). Tables and standalone math paragraphs are emitted as
    they appear.

    ``ole_blobs`` maps relationship ids to the raw bytes of every OLE
    object in the package — used to resolve ``<w:object>`` MathType /
    Equation 3.0 formulas to their MTEF payload. ``None`` skips OLE
    handling entirely (kept for callers that build a body element
    outside of :func:`parse_docx`).
    """
    if ole_blobs is None:
        ole_blobs = {}
    pending_list: list[ListItem] = []
    pending_list_ordered: bool | None = None

    def flush_list():
        nonlocal pending_list, pending_list_ordered
        if pending_list:
            yield List(
                ordered=bool(pending_list_ordered),
                items=pending_list,
            )
            pending_list = []
            pending_list_ordered = None

    for child in body:
        tag = _local(child.tag)
        if tag == "p":
            blocks = _convert_paragraph(child, ole_blobs=ole_blobs)
            for blk in blocks:
                if isinstance(blk, ListItem):
                    ordered = blk.id == "__ordered__"
                    blk.id = None  # carrier flag, not a real id
                    if pending_list_ordered is None:
                        pending_list_ordered = ordered
                    elif pending_list_ordered != ordered:
                        # Flavor changed (ordered ↔ unordered) → split.
                        yield from flush_list()
                        pending_list_ordered = ordered
                    pending_list.append(blk)
                else:
                    yield from flush_list()
                    yield blk
        elif tag == "tbl":
            yield from flush_list()
            yield _convert_table(child, ole_blobs=ole_blobs)
        elif tag == "oMathPara":
            yield from flush_list()
            yield _math_block_from_omath_para(child)
        else:
            # sectPr and unknown elements are ignored — they don't
            # carry braille-relevant content.
            continue
    yield from flush_list()


# ---------------------------------------------------------------------------
# Paragraph → Block
# ---------------------------------------------------------------------------


def _convert_paragraph(
    p: Element, *, ole_blobs: dict[str, bytes] | None = None
) -> list[Block]:
    """Convert a single ``<w:p>`` into one or more IR blocks.

    A paragraph that is **only** display math becomes a standalone
    :class:`MathBlock`. A paragraph mixing text + inline math becomes a
    :class:`Paragraph` (or :class:`Heading` / :class:`ListItem` based
    on style hints). Display-math children inside an otherwise-textual
    paragraph are extracted and emitted between paragraph slices so
    the math still renders as display, not inline.
    """
    if ole_blobs is None:
        ole_blobs = {}
    style = _paragraph_style(p)
    list_info = _paragraph_list_info(p, style=style)

    # First pass: split the paragraph at display-math boundaries.
    # Word allows ``m:oMathPara`` nested inside ``w:p``; treat each
    # one as a block boundary so display math gets its own block.
    text_parts: list[str] = []
    blocks_out: list[Block] = []

    def flush_text():
        nonlocal text_parts
        if text_parts:
            text = "".join(text_parts).strip()
            if text:
                blocks_out.append(
                    _wrap_text_block(text, style=style, list_info=list_info)
                )
            text_parts = []

    for run_text, math_block in _walk_paragraph_content(p, ole_blobs=ole_blobs):
        if math_block is not None:
            flush_text()
            blocks_out.append(math_block)
        else:
            text_parts.append(run_text)
    flush_text()

    # Empty paragraph: keep an empty Paragraph so the layout reflects
    # the blank line — users sometimes use these as visual spacing.
    if not blocks_out and not style and list_info is None:
        return [Paragraph(text="")]

    return blocks_out


def _wrap_text_block(
    text: str,
    *,
    style: str | None,
    list_info: tuple[int, bool] | None,
) -> Block:
    """Pick the right block class for a paragraph slice.

    Order of precedence: list info wins over heading style (Word lets
    a "Heading 1" paragraph be a list item — that's still a list item
    in our IR); explicit heading style wins over plain paragraph.

    The list item carries an internal ``__ordered__`` marker via
    :attr:`Block.id` so :func:`_iter_body_blocks` knows what flavour
    of list to wrap it in. The id is cleared before yielding.
    """
    if list_info is not None:
        _level, ordered = list_info
        item = ListItem(text=text)
        if ordered:
            item.id = "__ordered__"
        return item
    if style is not None:
        m = _HEADING_STYLE_RE.match(style)
        if m:
            level = int(m.group(1))
            return Heading(level=level, text=text)
    return Paragraph(text=text)


def _walk_paragraph_content(
    p: Element, *, ole_blobs: dict[str, bytes] | None = None
):
    """Yield ``(text_piece, math_block | None)`` for each content unit.

    ``text_piece`` is the contribution to surrounding paragraph text
    (empty string when the unit is a standalone display block).
    ``math_block`` is non-None only for display equations
    (``m:oMathPara`` children); inline ``m:oMath`` produces a text
    piece carrying ``$<math>...</math>$``.

    ``<w:object>`` elements containing a MathType / Equation 3.0 OLE
    object are extracted from ``ole_blobs`` and translated through the
    MTEF adapter into the same ``$<math>...</math>$`` inline form, so
    legacy formulas line up with native OMML ones downstream.

    Word EQ fields (``<w:fldChar begin>`` + ``<w:instrText>eq ...</w:instrText>``
    + ``<w:fldChar end>``) span multiple runs; an :class:`_FieldState`
    instance threads the in-flight ``instrText`` buffer across run
    boundaries so the EQ adapter sees the complete instruction.
    """
    if ole_blobs is None:
        ole_blobs = {}
    field_state = _FieldState()
    # Iterate top-level children only — ``.iter()`` would re-visit
    # nested elements once their parent has handled them.
    for child in p:
        tag = _local(child.tag)
        if tag == "oMathPara":
            yield "", _math_block_from_omath_para(child)
        elif tag == "oMath":
            yield _inline_math_as_text(child), None
        elif tag == "r":
            for piece in _walk_run(child, ole_blobs, field_state):
                yield piece, None
        elif tag == "hyperlink":
            # Hyperlinks wrap runs and may contain math too.
            for hyper_child in child:
                hyper_tag = _local(hyper_child.tag)
                if hyper_tag == "r":
                    for piece in _walk_run(hyper_child, ole_blobs, field_state):
                        yield piece, None
                elif hyper_tag == "oMath":
                    yield _inline_math_as_text(hyper_child), None
                elif hyper_tag == "object":
                    text = _ole_object_to_inline_math(hyper_child, ole_blobs)
                    if text:
                        yield text, None
        elif tag == "object":
            text = _ole_object_to_inline_math(child, ole_blobs)
            if text:
                yield text, None
        elif tag == "fldSimple":
            # Word's simple-field form: instruction in ``w:instr``
            # attribute, result text as children. Skip the result text
            # entirely since it's just Word's cached visual rendering.
            instr = child.get(_W_PREFIX + "instr") or child.get("instr") or ""
            piece = _eq_field_to_inline_math(instr)
            if piece is not None:
                yield piece, None
        elif tag == "AlternateContent":
            # Word wraps OLE objects in <mc:AlternateContent> when both
            # a modern (Choice) and legacy (Fallback) representation
            # exist. Prefer Fallback for OLE math — Choice is usually
            # the picture preview, which we can't read.
            for piece, math in _walk_alternate_content(child, ole_blobs):
                yield piece, math
        elif tag in ("pPr",):
            # Paragraph properties — already consumed by style / list
            # detection; skip here.
            continue
        else:
            # Unknown wrapping element — descend best-effort to find
            # text runs. Avoid descending into property sub-trees.
            for sub in child.iter():
                sub_tag = _local(sub.tag)
                if sub_tag == "t":
                    yield (sub.text or ""), None


# ---------------------------------------------------------------------------
# Word field state machine (EQ fields span multiple runs)
# ---------------------------------------------------------------------------


class _FieldState:
    """In-flight state for ``<w:fldChar>`` / ``<w:instrText>`` parsing.

    A Word field looks like::

        <w:r><w:fldChar w:fldCharType="begin"/></w:r>
        <w:r><w:instrText>eq \\f(1,2)</w:instrText></w:r>
        <w:r><w:fldChar w:fldCharType="separate"/></w:r>   ← optional
        <w:r><w:t>cached visible result</w:t></w:r>        ← skipped
        <w:r><w:fldChar w:fldCharType="end"/></w:r>

    The instruction text accumulates between ``begin`` and
    ``separate`` (or ``end`` if no separate). After ``separate`` we're
    in the cached-result section, which we discard because the
    authoritative content is the instruction itself. Nested fields are
    supported via ``depth``; only depth-1 EQ instructions are
    converted (nested ones are part of the outer instruction text).
    """

    __slots__ = ("depth", "after_separate", "instr_buf")

    def __init__(self) -> None:
        self.depth: int = 0
        self.after_separate: bool = False
        self.instr_buf: list[str] = []

    @property
    def in_field(self) -> bool:
        return self.depth > 0

    @property
    def collecting_instr(self) -> bool:
        """True iff we're inside a field but before its ``separate`` marker."""
        return self.depth > 0 and not self.after_separate

    def begin(self) -> None:
        if self.depth == 0:
            self.instr_buf = []
            self.after_separate = False
        self.depth += 1

    def separate(self) -> None:
        if self.depth > 0:
            self.after_separate = True

    def end(self) -> str | None:
        """Close one field level. Returns the assembled instruction
        text if a top-level field just closed, else None."""
        if self.depth == 0:
            return None
        self.depth -= 1
        if self.depth == 0:
            instr = "".join(self.instr_buf)
            self.instr_buf = []
            self.after_separate = False
            return instr
        return None

    def add_instr(self, text: str) -> None:
        if self.collecting_instr:
            self.instr_buf.append(text)


def _eq_field_to_inline_math(instr: str) -> str | None:
    """Parse ``instr`` as an EQ field, return ``$<math>...</math>$`` text.

    Returns ``None`` for non-EQ fields (HYPERLINK, PAGE, TOC, …) so
    the caller can skip them silently. The EQ adapter itself wraps
    parse failures in ``<merror>`` rather than raising, so even
    malformed equations come back as inline math (the backend will
    surface a MATH_ERROR warning).
    """
    text = instr.strip()
    if not text:
        return None
    # Field code is the first whitespace-delimited word.
    head = text.split(None, 1)[0].lower()
    if head != "eq":
        return None
    from brailix.frontend.math.registry import math_source_registry

    mathml = math_source_registry.get("eq_field").to_mathml(text)
    return "$" + _flatten_xml(mathml) + "$"


def _walk_run(
    r: Element,
    ole_blobs: dict[str, bytes],
    field_state: _FieldState | None = None,
):
    """Yield text pieces inside a ``<w:r>``, including any OLE objects.

    Word commonly nests ``<w:object>`` inside a run when the equation
    is inline with text. Returning a list keeps the caller's
    ``(text, math)`` contract intact — every yielded piece is a string
    that gets appended to the surrounding paragraph text.

    ``field_state`` (when provided) tracks ``w:fldChar`` boundaries
    across runs so EQ fields whose instruction spans multiple runs
    still parse correctly. Text inside the field's cached-result
    section (between ``separate`` and ``end``) is silently dropped so
    Word's visible-text fallback doesn't end up duplicated alongside
    the converted math.
    """
    parts: list[str] = []
    for child in r:
        tag = _local(child.tag)
        if tag == "fldChar":
            if field_state is None:
                continue
            ftype = child.get(_W_PREFIX + "fldCharType") or child.get("fldCharType")
            if ftype == "begin":
                field_state.begin()
            elif ftype == "separate":
                field_state.separate()
            elif ftype == "end":
                instr = field_state.end()
                if instr is not None:
                    piece = _eq_field_to_inline_math(instr)
                    if piece is not None:
                        parts.append(piece)
            continue
        if tag == "instrText":
            if field_state is not None and field_state.collecting_instr:
                field_state.add_instr(child.text or "")
            continue
        if field_state is not None and field_state.in_field and not field_state.collecting_instr:
            # Inside the field's cached-result section — drop everything
            # so the visual fallback doesn't end up doubling the math.
            continue
        if tag == "t":
            parts.append(child.text or "")
        elif tag == "br":
            parts.append("\n")
        elif tag == "tab":
            parts.append(" ")
        elif tag == "object":
            text = _ole_object_to_inline_math(child, ole_blobs)
            if text:
                parts.append(text)
        elif tag == "AlternateContent":
            for piece, _math in _walk_alternate_content(child, ole_blobs):
                if piece:
                    parts.append(piece)
    yield from parts


def _walk_alternate_content(
    alt: Element, ole_blobs: dict[str, bytes]
):
    """Walk an ``<mc:AlternateContent>`` for math content.

    Strategy: try Fallback first — that's where Word stores the legacy
    ``<w:object>`` form when also offering a modern drawing in Choice.
    Choice is descended only if Fallback yields nothing.
    """
    fallback = _first_local(alt, "Fallback")
    if fallback is not None:
        produced = False
        for piece, math in _walk_alt_subtree(fallback, ole_blobs):
            produced = True
            yield piece, math
        if produced:
            return
    for choice in alt:
        if _local(choice.tag) == "Choice":
            for piece, math in _walk_alt_subtree(choice, ole_blobs):
                yield piece, math


def _walk_alt_subtree(node: Element, ole_blobs: dict[str, bytes]):
    """Descend into an AlternateContent branch, surfacing math content.

    The branch can be any depth — Word sometimes nests another
    ``<w:r>`` or ``<w:p>`` here. We dispatch through the same machinery
    used by paragraph walking, just without the paragraph-level
    splitting (the caller's run/paragraph context already has that).
    """
    for child in node:
        tag = _local(child.tag)
        if tag == "object":
            text = _ole_object_to_inline_math(child, ole_blobs)
            if text:
                yield text, None
        elif tag == "oMath":
            yield _inline_math_as_text(child), None
        elif tag == "oMathPara":
            yield "", _math_block_from_omath_para(child)
        elif tag == "r":
            for piece in _walk_run(child, ole_blobs):
                yield piece, None
        else:
            # Recurse — the OLE might be wrapped in another shape /
            # drawing element we don't directly handle.
            yield from _walk_alt_subtree(child, ole_blobs)


def _math_block_from_omath_para(node: Element) -> MathBlock:
    """Wrap a standalone display equation in a :class:`MathBlock`.

    The block carries the raw OMML XML; the math frontend's OMML
    adapter does the conversion at Pipeline time. Keeping the
    conversion lazy here (rather than pre-MathML'ing) keeps the input
    layer's job simple — "extract structure", not "translate dialects".
    """
    omml_xml = _serialize(node)
    return MathBlock(source="omml", text=omml_xml)


# ---------------------------------------------------------------------------
# Style + list info
# ---------------------------------------------------------------------------


def _paragraph_style(p: Element) -> str | None:
    """Read ``w:pPr/w:pStyle@w:val`` — the paragraph style name.

    Returns the raw style id Word stored (e.g. ``"Heading1"``). The
    heading detector matches both ``"Heading 1"`` and ``"Heading1"``
    via :data:`_HEADING_STYLE_RE`.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is None:
        return None
    style = _first(pPr, _W_PREFIX + "pStyle")
    if style is None:
        return None
    return style.get(_W_PREFIX + "val")


def _paragraph_list_info(
    p: Element, *, style: str | None = None
) -> tuple[int, bool] | None:
    """Return ``(level, ordered)`` if the paragraph is a list item,
    else ``None``.

    Two signals are accepted:

    * ``w:pPr/w:numPr`` — real Word numbering. The ``ilvl`` element
      gives the nesting depth; the ``numId`` → ``abstractNumId`` →
      ``lvl`` / ``numFmt`` chain in ``word/numbering.xml`` would tell
      us ordered vs unordered, but resolving that is out of scope for
      this V1.  Default to unordered.
    * ``w:pPr/w:pStyle`` named one of Word's built-in list styles
      (``ListBullet``, ``ListNumber``, ``ListNumber2``, ``ListDash``,
      ``ListParagraph``, ``ListContinue``).  python-docx applies these
      without creating a numPr, so we have to look at the style name
      to recognise them.

    The pStyle-only path is the common case for documents written by
    python-docx; the numPr path is the common case for documents
    edited in Word.  Either way the braille renderer treats list
    items uniformly — item position drives the marker, not visual
    style — so the approximate ordered detection here is harmless.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is not None:
        numPr = _first(pPr, _W_PREFIX + "numPr")
        if numPr is not None:
            ilvl_elem = _first(numPr, _W_PREFIX + "ilvl")
            ilvl = (
                int(ilvl_elem.get(_W_PREFIX + "val"))
                if ilvl_elem is not None else 0
            )
            return ilvl, False
    if style:
        m = _LIST_STYLE_RE.match(style)
        if m:
            family = m.group(1).lower()
            depth = int(m.group(2)) if m.group(2) else 1
            ordered = family == "number"
            return max(0, depth - 1), ordered
    return None


# ---------------------------------------------------------------------------
# Table
# ---------------------------------------------------------------------------


def _convert_table(
    tbl: Element, *, ole_blobs: dict[str, bytes] | None = None
) -> Table:
    rows: list[TableRow] = []
    for tr in tbl:
        if _local(tr.tag) != "tr":
            continue
        cells: list[TableCell] = []
        for tc in tr:
            if _local(tc.tag) != "tc":
                continue
            cells.append(_convert_table_cell(tc, ole_blobs=ole_blobs))
        if cells:
            rows.append(TableRow(cells=cells))
    return Table(rows=rows)


def _convert_table_cell(
    tc: Element, *, ole_blobs: dict[str, bytes] | None = None
) -> TableCell:
    """Flatten a cell's paragraphs into one TableCell text.

    The braille table renderer expects flat cell text (no nested
    paragraphs); we join paragraph contents with a newline so a
    multi-paragraph cell still preserves the visual break.
    """
    parts: list[str] = []
    for child in tc:
        if _local(child.tag) != "p":
            continue
        paragraph_blocks = _convert_paragraph(child, ole_blobs=ole_blobs)
        for blk in paragraph_blocks:
            if isinstance(blk, MathBlock):
                # Surface OMML as inline math by round-tripping through
                # the same ``$<math>...</math>$`` form used for inline
                # equations. Tables are visually constrained — display
                # math doesn't fit anyway.
                from brailix.frontend.math.registry import math_source_registry
                mathml = math_source_registry.get("omml").to_mathml(blk.text or "")
                parts.append("$" + _flatten_xml(mathml) + "$")
            else:
                parts.append(blk.text or "")
    return TableCell(text="\n".join(p for p in parts if p))
