"""OOXML paragraph-property readers for the docx adapter.

Pure ``w:pPr`` accessors the body walker consults: paragraph style,
alignment, and list-item level / ordering. They depend only on the XML
helpers in :mod:`._xml`, so they are kept out of the block-walking
pipeline in :mod:`._blocks` and can be read (and tested) on their own.
"""

from __future__ import annotations

import re

from brailix.input.docx._xml import (
    _W_PREFIX,
    Element,
    _first,
    _ns_attr,
)

# Word lets a paragraph be a list item via either ``numPr`` (real
# numbering with a definition) or just a list-flavoured pStyle (eg.
# ``ListBullet``, ``ListNumber1``).  The style-only path is common in
# documents generated by python-docx or by Word's "Apply Style"
# command without explicit numbering, so we detect both.  The regex
# below matches the bullet / number / dash / continuation variants
# Word ships out of the box plus their numbered siblings (``ListNumber``,
# ``ListNumber2``, ...).
_LIST_STYLE_RE = re.compile(
    r"^list\s*(bullet|number|dash|paragraph|continue)(\d*)$",
    re.IGNORECASE,
)


def _paragraph_style(p: Element) -> str | None:
    """Read ``w:pPr/w:pStyle@w:val`` — the paragraph style name.

    Returns the raw style id Word stored (e.g. ``"Heading1"``). The
    heading detector in :mod:`._blocks` matches both ``"Heading 1"`` and
    ``"Heading1"`` (via its ``_HEADING_STYLE_RE``).
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is None:
        return None
    style = _first(pPr, _W_PREFIX + "pStyle")
    if style is None:
        return None
    # Qualified ``w:val`` first, bare ``val`` fallback — same two-step every
    # other OOXML attribute read here uses. Some emitters drop the prefix on
    # pStyle@val; reading only the qualified form silently lost heading/list
    # detection (the style name came back None, so the paragraph degraded to
    # plain body text).
    return _ns_attr(style, _W_PREFIX, "val")


# OOXML ``w:jc@w:val`` → the alignments braille layout can act on. Word
# 2013+ writes the LTR-relative ``start`` / ``end``; older files use
# ``left`` / ``right``. Only ``center`` and ``right`` (and ``end``, right's
# relative spelling) map to something — ``left`` / ``start`` are the default
# and ``both`` (justified) / ``distribute`` / the kashida variants have no
# braille convention, so all of those are absent and fall through to ``None``.
_JC_ALIGN = {
    "center": "center",
    "right": "right",
    "end": "right",
}


def _paragraph_alignment(p: Element) -> str | None:
    """Return the braille-relevant alignment of ``<w:p>``, or ``None``.

    Reads ``w:pPr/w:jc@w:val`` and maps it through :data:`_JC_ALIGN`. Only
    ``center`` and ``right`` survive — the two horizontal placements braille
    layout has a convention for. ``left`` / ``start`` (the default) and
    ``both`` / ``distribute`` (no braille analogue) all yield ``None``, so
    the paragraph reads flush-left exactly like untagged prose and no align
    marker is carried needlessly.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is None:
        return None
    jc = _first(pPr, _W_PREFIX + "jc")
    if jc is None:
        return None
    val = _ns_attr(jc, _W_PREFIX, "val")
    return _JC_ALIGN.get((val or "").lower())


def _ilvl_value(ilvl_elem: Element | None) -> int:
    """Parse ``w:ilvl@w:val`` to a 0-based list level, defaulting to 0.

    Tolerates a missing element, a missing / blank ``val`` (some emitters
    write a bare ``val`` with no ``w:`` prefix — mirror the ``or .get("val")``
    fallback used elsewhere here), and a non-integer value. None of those
    should crash list detection; the old ``int(ilvl_elem.get(...))`` raised
    ``TypeError`` on a missing or bare ``val``.
    """
    if ilvl_elem is None:
        return 0
    raw = _ns_attr(ilvl_elem, _W_PREFIX, "val")
    if not raw:
        return 0
    try:
        return max(0, int(raw))
    except ValueError:
        return 0


def _paragraph_list_info(
    p: Element, *, style: str | None = None
) -> tuple[int, bool] | None:
    """Return ``(level, ordered)`` if the paragraph is a list item,
    else ``None``.

    Two signals are accepted:

    * ``w:pPr/w:numPr`` — real Word numbering. The ``ilvl`` element
      gives the nesting depth; the ``numId`` → ``abstractNumId`` →
      ``lvl`` / ``numFmt`` chain in ``word/numbering.xml`` would tell
      us ordered vs unordered, but resolving that is out of scope for
      this V1.  Default to unordered.
    * ``w:pPr/w:pStyle`` named one of Word's built-in list styles
      (``ListBullet``, ``ListNumber``, ``ListNumber2``, ``ListDash``,
      ``ListParagraph``, ``ListContinue``).  python-docx applies these
      without creating a numPr, so we have to look at the style name
      to recognise them.

    The pStyle-only path is the common case for documents written by
    python-docx; the numPr path is the common case for documents
    edited in Word.  Either way the braille renderer treats list
    items uniformly — item position drives the marker, not visual
    style — so the approximate ordered detection here is harmless.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is not None:
        numPr = _first(pPr, _W_PREFIX + "numPr")
        if numPr is not None:
            ilvl_elem = _first(numPr, _W_PREFIX + "ilvl")
            return _ilvl_value(ilvl_elem), False
    if style:
        m = _LIST_STYLE_RE.match(style)
        if m:
            family = m.group(1).lower()
            depth = int(m.group(2)) if m.group(2) else 1
            ordered = family == "number"
            return max(0, depth - 1), ordered
    return None
